"use client";

import { useEffect, useState } from "react";
import Navbar from "@/components/Navbar";
import NewsCard from "@/components/NewsCard";
import Loader from "@/components/Loader";
import CategoryFilter from "@/components/CategoryFilter";
import { newsApi, NewsArticle } from "@/lib/api";

export default function Home() {
  const [articles, setArticles] = useState<NewsArticle[]>([]);
  const [categories, setCategories] = useState<string[]>([]);
  const [loading, setLoading] = useState(true);
  const [categoriesLoading, setCategoriesLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const [searchQuery, setSearchQuery] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [categoriesError, setCategoriesError] = useState<string | null>(null);
  const [backendStatus, setBackendStatus] = useState<"checking" | "online" | "offline">("checking");
  const presetCategories = ["AI", "Robotics", "AI Tool", "Innovations", "LLMs"];

  const fetchNews = async () => {
    try {
      setError(null);
      setLoading(true);
      const data = await newsApi.getLatest({
        limit: 50,
        category: selectedCategory || undefined,
        search: searchQuery || undefined,
      });
      setArticles(data || []);
    } catch (error: any) {
      console.error("Error fetching news:", error);
      setError(
        error?.response?.data?.detail || 
        error?.message || 
        "Failed to fetch news. Make sure the backend server is running on http://localhost:8000"
      );
      setArticles([]);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  };

  const fetchCategories = async () => {
    try {
      setCategoriesLoading(true);
      setCategoriesError(null);
      const data = await newsApi.getCategories();
      setCategories(data || []);
    } catch (error: any) {
      console.error("Error fetching categories:", error);
      setCategoriesError(
        error?.response?.data?.detail || 
        error?.message || 
        "Failed to fetch categories"
      );
      setCategories([]);
    } finally {
      setCategoriesLoading(false);
    }
  };

  const handleRefresh = async () => {
    setRefreshing(true);
    try {
      await newsApi.fetchNews();
      // Wait a bit for processing, then fetch latest
      setTimeout(() => {
        fetchNews();
      }, 2000);
    } catch (error) {
      console.error("Error refreshing news:", error);
      setRefreshing(false);
    }
  };

  useEffect(() => {
    // Check backend health
    const checkBackend = async () => {
      try {
        await newsApi.health();
        setBackendStatus("online");
      } catch (error) {
        setBackendStatus("offline");
      }
    };
    checkBackend();
    fetchCategories();
  }, []);

  useEffect(() => {
    // Safety timeout to prevent infinite loading
    let timeoutCleared = false;
    const timeoutId = setTimeout(() => {
      if (!timeoutCleared) {
        setLoading(false);
        setError("Request timed out. The backend may not be responding. Check if the server is running.");
      }
    }, 15000); // 15 second timeout

    fetchNews().finally(() => {
      timeoutCleared = true;
      clearTimeout(timeoutId);
    });

    return () => {
      timeoutCleared = true;
      clearTimeout(timeoutId);
    };
  }, [selectedCategory, searchQuery]);

  return (
    <div className="min-h-screen">
      <Navbar />
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 space-y-8">
        <section className="relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-slate-900/80 via-slate-900/50 to-slate-900/70 p-8 shadow-2xl shadow-sky-500/10">
          <div className="absolute inset-0 pointer-events-none">
            <div className="absolute -top-20 -right-20 h-64 w-64 bg-sky-500/30 rounded-full blur-3xl"></div>
            <div className="absolute -bottom-24 -left-10 h-64 w-64 bg-emerald-400/25 rounded-full blur-3xl"></div>
          </div>
          <div className="relative flex flex-col lg:flex-row gap-8 items-start lg:items-center">
            <div className="flex-1 space-y-4">
              <p className="text-sm uppercase tracking-[0.3em] text-emerald-200/80">AI-curated</p>
              <h1 className="text-4xl sm:text-5xl font-bold text-white leading-tight">
                AI Desk — your real-time intelligence radar
              </h1>
              <p className="text-slate-200/80 max-w-2xl">
                Summaries, keywords, and categories generated by AI so you can scan the signal, not the noise.
              </p>
              <div className="flex flex-wrap gap-3">
                <div className="px-4 py-2 rounded-xl bg-white/5 border border-white/10 text-sm text-emerald-100 flex items-center gap-2">
                  <span className="w-2 h-2 rounded-full bg-emerald-300 animate-pulse"></span>
                  {backendStatus === "checking" && "Checking backend..."}
                  {backendStatus === "online" && "Backend online"}
                  {backendStatus === "offline" && "Backend offline"}
                </div>
                <button
                  onClick={handleRefresh}
                  disabled={refreshing}
                  className="px-5 py-2 rounded-xl bg-gradient-to-r from-sky-500 via-emerald-400 to-cyan-400 text-slate-900 font-semibold shadow-lg shadow-emerald-400/30 disabled:opacity-60"
                >
                  {refreshing ? "Refreshing…" : "Refresh feed"}
                </button>
              </div>
            </div>
            <div className="w-full lg:w-80 glass-panel rounded-2xl p-5 text-white space-y-3">
              <p className="text-sm text-slate-200/70">System insight</p>
              <div className="flex items-center gap-3">
                <div className="h-12 w-12 rounded-2xl bg-gradient-to-br from-sky-400 to-emerald-300 flex items-center justify-center text-slate-900 font-bold">
                  ⚡
                </div>
                <div>
                  <p className="text-xl font-semibold">AI Signal Boost</p>
                  <p className="text-xs text-slate-200/70">Summaries distilled via LLM</p>
                </div>
              </div>
              <div className="grid grid-cols-3 gap-3 text-center">
                <div className="rounded-xl border border-white/10 p-3">
                  <p className="text-2xl font-bold text-emerald-200">{articles.length}</p>
                  <p className="text-[11px] text-slate-200/70">articles</p>
                </div>
                <div className="rounded-xl border border-white/10 p-3">
                  <p className="text-2xl font-bold text-sky-200">{categories.length}</p>
                  <p className="text-[11px] text-slate-200/70">categories</p>
                </div>
                <div className="rounded-xl border border-white/10 p-3">
                  <p className="text-2xl font-bold text-indigo-200">~15s</p>
                  <p className="text-[11px] text-slate-200/70">avg fetch</p>
                </div>
              </div>
            </div>
          </div>
          <div className="mt-6">
            <div className="flex flex-col md:flex-row gap-3 md:items-center">
              <div className="flex-1 relative">
                <input
                  type="text"
                  placeholder="Search titles or keywords instantly…"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="w-full px-4 py-3 rounded-xl bg-white/5 border border-white/10 text-white placeholder:text-slate-300/60 focus:ring-2 focus:ring-emerald-300 focus:border-transparent"
                />
                <div className="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-slate-200/70 bg-white/5 px-2 py-1 rounded-lg border border-white/10">
                  Cmd/Ctrl + K
                </div>
              </div>
              <div className="flex gap-3 flex-wrap items-center">
                <div className="bg-white/5 border border-white/10 rounded-xl px-3 py-2 text-slate-100 text-sm flex items-center gap-2">
                  <span className="text-slate-300/80">Quick category</span>
                  <select
                    value={selectedCategory || ""}
                    onChange={(e) => setSelectedCategory(e.target.value || null)}
                    className="bg-transparent border border-white/10 rounded-lg px-2 py-1 text-xs focus:outline-none"
                  >
                    <option value="">All</option>
                    {presetCategories.map((cat) => (
                      <option key={cat} value={cat}>
                        {cat}
                      </option>
                    ))}
                  </select>
                </div>
                <div className="flex gap-2 flex-wrap">
                  <span className="px-3 py-2 rounded-lg text-xs font-semibold text-slate-100 bg-white/5 border border-white/10">
                    Trending: AGI
                  </span>
                  <span className="px-3 py-2 rounded-lg text-xs font-semibold text-slate-100 bg-white/5 border border-white/10">
                    Agents
                  </span>
                  <span className="px-3 py-2 rounded-lg text-xs font-semibold text-slate-100 bg-white/5 border border-white/10">
                    Multimodal
                  </span>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Category Selection Section */}
        <div className="mb-4">
          <div className="flex items-center justify-between mb-3">
            <h2 className="text-lg font-semibold text-white">Filter by Category</h2>
            {selectedCategory && (
              <button
                onClick={() => setSelectedCategory(null)}
                className="text-sm text-emerald-200 hover:underline"
              >
                Clear Filter
              </button>
            )}
          </div>

          {categoriesLoading ? (
            <div className="flex items-center gap-2 text-slate-200/80">
              <div className="w-4 h-4 border-2 border-blue-200 border-t-blue-600 rounded-full animate-spin"></div>
              <span>Loading categories...</span>
            </div>
          ) : categoriesError ? (
            <div className="p-3 bg-yellow-500/10 border border-yellow-300/30 rounded-lg">
              <p className="text-yellow-100 text-sm">
                {categoriesError}
              </p>
            </div>
          ) : categories.length > 0 ? (
            <div className="space-y-4">
              {/* Dropdown for mobile/small screens */}
              <div className="block md:hidden">
                <select
                  value={selectedCategory || ""}
                  onChange={(e) => setSelectedCategory(e.target.value || null)}
                  className="w-full px-4 py-2 border border-gray-300 dark:border-gray-700 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-800 dark:text-white"
                >
                  <option value="">All Categories</option>
                  {categories.map((category) => (
                    <option key={category} value={category}>
                      {category}
                    </option>
                  ))}
                </select>
              </div>

              {/* Chip buttons for desktop */}
              <div className="hidden md:block">
                <CategoryFilter
                  categories={categories}
                  selectedCategory={selectedCategory}
                  onCategoryChange={setSelectedCategory}
                />
              </div>
            </div>
          ) : (
            <div className="p-3 bg-white/5 border border-white/10 rounded-lg">
              <p className="text-slate-200/80 text-sm">
                No categories available yet. Click "Refresh News" to fetch articles and generate categories.
              </p>
            </div>
          )}

          {selectedCategory && (
            <div className="mt-3 p-3 bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 rounded-lg flex items-center justify-between">
              <p className="text-sm text-blue-800 dark:text-blue-200">
                <span className="font-semibold">Filtered:</span> Showing articles in category{" "}
                <span className="font-bold">{selectedCategory}</span>
                {articles.length > 0 && (
                  <span className="ml-2">({articles.length} article{articles.length !== 1 ? "s" : ""})</span>
                )}
              </p>
              <button
                onClick={() => setSelectedCategory(null)}
                className="text-xs text-emerald-200 hover:underline font-medium"
              >
                Show All
              </button>
            </div>
          )}
        </div>

        {error && (
          <div className="mb-6 p-4 bg-red-500/10 border border-red-300/30 rounded-lg">
            <p className="text-red-100 font-medium">Error: {error}</p>
            <p className="text-red-200 text-sm mt-2">
              Make sure the backend server is running: <code className="bg-white/5 px-2 py-1 rounded border border-white/10">python run.py</code> in the backend directory
            </p>
          </div>
        )}

        {loading ? (
          <Loader />
        ) : articles.length === 0 && !error ? (
          <div className="text-center py-12">
            <p className="text-slate-200/80 text-lg mb-4">
              No articles found. The database might be empty.
            </p>
            <button
              onClick={handleRefresh}
              className="px-6 py-2 bg-gradient-to-r from-sky-500 to-emerald-400 text-slate-900 font-semibold rounded-lg hover:opacity-90 transition"
            >
              Fetch News Now
            </button>
          </div>
        ) : articles.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {articles.map((article) => (
              <NewsCard key={article.id} article={article} />
            ))}
          </div>
        ) : null}
      </main>
    </div>
  );
}

